// Initial stock take, from Mataatua_Kitchen_inventory.docx.
// Only used to populate the database the very first time it's empty —
// after that, everything lives in Supabase and this file is never read again.
window.SEED_DATA = [
  // Kitchen
  { category: "Kitchen", name: "Dinner plates", quantity: 122 },
  { category: "Kitchen", name: "Pudding plates", quantity: 179 },
  { category: "Kitchen", name: "Bread plates", quantity: 71 },
  { category: "Kitchen", name: "Cups", quantity: 0 },
  { category: "Kitchen", name: "Yellow platters", quantity: 32 },
  { category: "Kitchen", name: "Yellow dinner plates", quantity: 22 },
  { category: "Kitchen", name: "Butter dishes", quantity: 58 },
  { category: "Kitchen", name: "Caraffees", quantity: 48 },
  { category: "Kitchen", name: "Saucers", quantity: 86 },
  { category: "Kitchen", name: "Gastro dishes", quantity: 27 },
  { category: "Kitchen", name: "Gastro lids", quantity: 26 },
  { category: "Kitchen", name: "Trays", quantity: 11 },
  { category: "Kitchen", name: "Tray lids", quantity: 10 },
  { category: "Kitchen", name: "Chaffing dishes", quantity: 9 },
  { category: "Kitchen", name: "Chaffing stands", quantity: 10 },
  { category: "Kitchen", name: "Draining tray (strainers)", quantity: 2 },
  { category: "Kitchen", name: "White bowls", quantity: 11 },
  { category: "Kitchen", name: "Small white bowls", quantity: 10 },
  { category: "Kitchen", name: "Silver bowls (XL)", quantity: 5 },
  { category: "Kitchen", name: "Silver bowls (L)", quantity: 5 },
  { category: "Kitchen", name: "Silver bowls (S)", quantity: 12 },
  { category: "Kitchen", name: "Black bowls", quantity: 11 },
  { category: "Kitchen", name: "Glass bowls", quantity: 36 },
  { category: "Kitchen", name: "White serving bowls/lids/stands", quantity: 10 },
  { category: "Kitchen", name: "Small blue bowls", quantity: 15 },
  { category: "Kitchen", name: "Tea pots/lids", quantity: 7 },
  { category: "Kitchen", name: "Graters", quantity: 3 },
  { category: "Kitchen", name: "Jugs", quantity: 8 },
  { category: "Kitchen", name: "Large black heater", quantity: 1 },
  { category: "Kitchen", name: "Cutlery holders", quantity: 7 },
  { category: "Kitchen", name: "Large blue platters", quantity: 3 },
  { category: "Kitchen", name: "Large masher", quantity: 1 },
  { category: "Kitchen", name: "Ladle", quantity: 3 },
  { category: "Kitchen", name: "Fork (serving)", quantity: 3 },
  { category: "Kitchen", name: "Spatula", quantity: 3 },
  { category: "Kitchen", name: "Measuring spoons", quantity: 1 },
  { category: "Kitchen", name: "Can opener", quantity: 1 },
  { category: "Kitchen", name: "Egg beater", quantity: 1 },
  { category: "Kitchen", name: "Wooden spoons", quantity: 2 },
  { category: "Kitchen", name: "Spoons (serving)", quantity: 7 },
  { category: "Kitchen", name: "Egg flipper", quantity: 1 },
  { category: "Kitchen", name: "Whisk", quantity: 1 },
  { category: "Kitchen", name: "Knives (kitchen)", quantity: 10 },
  { category: "Kitchen", name: "Large tongs", quantity: 2 },
  { category: "Kitchen", name: "Tongs", quantity: 11 },
  { category: "Kitchen", name: "Straining scoop", quantity: 1 },
  { category: "Kitchen", name: "Teaspoons", quantity: 7 },
  { category: "Kitchen", name: "Spoons (cutlery)", quantity: 194 },
  { category: "Kitchen", name: "Knives (cutlery)", quantity: 179 },
  { category: "Kitchen", name: "Forks (cutlery)", quantity: 175 },

  // Bedding — Mataatua, Te Whai o te motu
  { category: "Bedding", name: "Mattresses", quantity: 65 },
  { category: "Bedding", name: "Pillows", quantity: 72 },
];
